name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0


      - name: Install X11 dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Install OpenGL dependencies
        run: sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            build
            ~/.ccache
          key: linux-build-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            linux-build-${{ runner.os }}-

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        working-directory: build
        run: cmake -S .. -B .

      - name: Build
        working-directory: build
        run: cmake --build . -- -j$(nproc)

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure || true
