name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0


      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            build
            ~/Library/Caches/ccache
          key: macos-build-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            macos-build-${{ runner.os }}-

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        working-directory: build
        run: cmake -S .. -B .

      - name: Build
        working-directory: build
        run: cmake --build . -- -j$(sysctl -n hw.ncpu)

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure || true
