name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake
        working-directory: build
        run: cmake -S .. -B .

      - name: Build
        working-directory: build
        run: make -j$(nproc)

      # Optional: Run tests if you have them (ctest looks for CMake tests)
      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure
