name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake
        working-directory: build
        run: cmake -S .. -B .

      - name: Build
        working-directory: build
        run: cmake --build . -- -j$(nproc)

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure || true
