name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0


      - name: Restore .NET dependencies
        run: dotnet restore
        working-directory: external/DiligentEngine/DiligentSamples/Tutorials/Tutorial03_Texturing-DotNet


      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            build
            C:\Users\runneradmin\AppData\Local\ccache
          key: windows-build-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            windows-build-${{ runner.os }}-

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake
        working-directory: build
        run: cmake -S .. -B .

      - name: Build
        working-directory: build
        run: cmake --build . -- /m

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure || true
